# Environnement PROD : 3 répliques, logs restreints, ressources renforcées.
replicaCount: 3

config:
  aspnetcoreEnvironment: Production
  logLevel: Warning

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
