apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-app.fullname" . }}-config
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: {{ .Values.config.aspnetcoreUrls | quote }}
  ConnectionStrings__DefaultConnection: {{ .Values.config.connectionString | quote }}
  Logging__LogLevel__Default: {{ .Values.config.logLevel | quote }}
