apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}-nginx
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
      {{- end }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.nginx.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.nginx.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.nginx.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.nginx.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.nginx.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.nginx.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "devops-app.fullname" . }}-nginx-config
